food/urls.py
from django.urls import path
from . import views, models

urlpatterns = [
    path('recipe_list/', views.RecipeListView.as_view(), name='recipe_list'),
    path('recipe/<int:pk>/',views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('add_recipe/', views.RecipeCreateView.as_view(), name='add_recipe'),
    path('recipe/<int:pk>/add_ingredient/', views.IngredientCreateView.as_view(), name='add_ingredient'),
    path('recipe/<int:pk>/delete/', views.RecipeDeleteView.as_view(), name='delete_recipe'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('clothes.urls')),
    path('', include('todo.urls')),
    path('', include('parser_app.urls')),
    path('', include('users.urls')),
    path('', include('food.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User

Junior_club = 'Junior'
Middle_club = 'Middle'
Senior_club = 'Senior'

class CustomUser(User):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )
    age = models.IntegerField(null=True, blank=True)
    phone_number = models.CharField(max_length=14, default='+996000000000')
    whats_phone = models.CharField(max_length=14, default='+996000000000')
    experience = models.PositiveIntegerField(default=2)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Male')
    club = models.CharField(max_length=100,null=True, blank=True)

    def save(self, *args, **kwargs):
        if 0 < self.experience <= 3:
            self.club = Junior_club
        elif 3 < self.experience <= 6:
            self.club = Middle_club
        elif 6 < self.experience <= 50:
            self.club = Senior_club
        else:
            self.club = None
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models

GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Введите Email')
    age = forms.IntegerField(required=True, label='Укажите ваш возраст')
    phone = forms.CharField(required=True, label='Введите номер телефона')
    whats_phone = forms.CharField(required=True, label='Введите ваш WhatsApp номер')
    experience = forms.IntegerField(required=True, label='Укажите ваш опыт')
    gender = forms.ChoiceField(choices=GENDER_CHOICES, label='Укажите пол')

    class Meta:
        model = models.CustomUser
        fields = ('username',
                  'email',
                  'password1',
                  'password2','first_name',
                  'last_name' ,
                  'age',
                  'phone',
                  'whats_phone',
                  'experience',
                  'gender')
        def save(self, commit=True):
            user = super().save(commit=False)
            user.email = self.cleaned_data['email']
            user.phone = self.cleaned_data['phone']
            user.experience = self.cleaned_data['experience']
            user.gender = self.cleaned_data['gender']

            if commit:
                user.save()
            return user

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView
from . import models, forms

class RegistrationView(CreateView):
    form_class = forms.RegistrationForm
    template_name = 'user/registration.html'
    success_url = reverse_lazy('users:login')

class AuthLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'user/login.html'
    success_url = reverse_lazy('users:user_list')

class AuthLogoutView(LogoutView):
    next_page = reverse_lazy('users:login')

class UserListView(ListView):
    template_name = 'user/user_list.html'
    context_object_name = 'users'
    model = models.CustomUser

    def get_queryset(self):
        return models.CustomUser.objects.all()

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<form method="POST" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'users:user_list' %}">Авторизация</a>
    <a href="{% url 'users:register' %}">Регистрация</a>

</form>
</body>
</html>

templates/user/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Регистрация</h1>
<form method="POST" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
    <button type="reset">Очистить</button>
</form>
</body>
</html>

templates/user/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Добро пожаловать</h1>
    <ol>
        {% for i in users %}
        <li>
            <p>{{ i.username }}</p>
            <p>{{ i.age }}</p>
            <p>{{ i.experience}}</p>
            {% if i.club %}
            <p>Этот человек в клубе - {{ i.club }}</p>
            {% else %}
            <p>Клуб не определен</p>
            {%endif%}
        </li>
        {% endfor %}
    </ol>


<form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Выйти из аккаунта</button>
</form>

</body>
</html>